name: CI - Rodar Testes com Pytest



on:

  push:

    branches:

      - main

  pull_request:

    branches:

      - main



jobs:

  test:

    runs-on: ubuntu-latest



    steps:

      - name: Clonar o repositório

        uses: actions/checkout@v3



      - name: Configurar o ambiente Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.10'



      - name: Instalar dependências

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt



      - name: Executar testes com pytest

        run: pytest --maxfail=1 --disable-warnings

